# Generated by Django 5.2.12 on 2026-04-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='qualityqcfa',
            name='quality_dat_week_te_e52a_idx',
        ),
        migrations.AddIndex(
            model_name='qualityqcfa',
            index=models.Index(fields=['week', 'team'], name='idx_qcfa_team_pof'),
        ),
    ]
