# Generated by Django 5.2.12 on 2026-04-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelSyncSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed and applied'), ('rejected', 'Rejected by user')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qc_fa_plant_data', models.JSONField(default=list)),
                ('qc_fa_customer_data', models.JSONField(default=list)),
                ('seconds_a4_data', models.JSONField(default=list)),
                ('seconds_general_data', models.JSONField(default=list)),
                ('container_data', models.JSONField(default=list)),
                ('qc_fa_plant_preview', models.JSONField(default=dict)),
                ('qc_fa_customer_preview', models.JSONField(default=dict)),
                ('seconds_a4_preview', models.JSONField(default=dict)),
                ('seconds_general_preview', models.JSONField(default=dict)),
                ('container_preview', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
