# Generated by Django 6.0.3 on 2026-04-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='qualityqcfa',
            new_name='quality_dat_week_ab94c5_idx',
            old_name='quality_dat_week_te_e52a_idx',
        ),
    ]
