# Generated by Django 6.0.3 on 2026-04-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_data', '0004_normalize_seconds_general'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='qualityqcfa',
            index=models.Index(fields=['table_type', 'date_1', 'po', 'style', 'team', 'color'], name='idx_qcfa_natural_lookup'),
        ),
    ]
