# Generated by Django 6.0.3 on 2026-04-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_data', '0005_add_qcfa_composite_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelsyncsession',
            name='redis_stored',
            field=models.BooleanField(default=False, help_text='True when raw row data is stored in Redis instead of JSONFields.'),
        ),
    ]
