# Generated by Django 6.0.3 on 2026-05-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_data', '0006_add_redis_stored_to_session'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='qualityqcfa',
            name='idx_qcfa_natural_lookup',
        ),
        migrations.AddField(
            model_name='qualityqcfa',
            name='line_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='qualityqcfa',
            index=models.Index(fields=['table_type', 'date_1', 'po', 'style', 'team', 'color', 'line_code'], name='idx_qcfa_natural_lookup'),
        ),
    ]
