# Generated by Django 6.0.3 on 2026-05-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_data', '0007_add_line_code_to_qualityqcfa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondsgeneral',
            name='line',
        ),
        migrations.AddField(
            model_name='secondsgeneral',
            name='line_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='secondsgeneral',
            name='team',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
