SHEET_NAMES = [
    ("QC FA Plant", 2, 67),
    ("QC FA Customer", 0, 64),
    ("SecondsA4", 1, 22),
    ("Seconds General", 1, 22),
    ("Container", 2, 24),
]

QC_FA_PLANT_REMAP = {
    'Date': 'date_1',
    'Week': 'week',
    'Customer': 'customer',
    'Team': 'team',
    'COORD.': 'coord',
    'Date2': 'date_2',
    'Po': 'po',
    'Style': 'style',
    'Batch': 'batch',
    'Color': 'color',
    'Qty': 'qty',
    'Seconds': 'seconds',
    'Accepted': 'accepted',
    'Rejected': 'rejected',
    'Sample': 'sample',
    'Defects': 'defeacts',
    'AQL %': 'aql',
    'Pass/Fail': 'pass_or_fail',
    'Uneven': 'uneven',
    'Broken Stitch': 'broken_stitch',
    'Open seam': 'open_seam',
    'Tear': 'tear',
    'Hi Low': 'hi_low',
    'Run Off Stitch': 'run_off_stitch',
    'Raw Edge': 'raw_edge',
    'Needle Holes': 'neddle_holes',
    'Loose Thread': 'loose_thread',
    'Uncut Thread': 'uncut_thread',
    'Big/Litter Neck': 'big_or_littler_neck',
    'Uneven Neck / Sleeve': 'uneven_neck_or_sleeve',
    'Out of Measurements': 'out_of_measurements',
    'incorrect Stitch': 'incorrect_stitch',
    'Variation Tension Stitch': 'variation_tension_sttich',
    'Excess Fabric': 'excess_fabric',
    'Hitched': 'hitched',
    'PO Mixed': 'po_midex',
    'Transfer Peel off, Leve': 'transfer_peel_off_or_leave',
    'Wrong Transfer': 'wrong_transfer',
    'Wrong  Label': 'wrong_label',
    ' Missing Transfer': 'missing_transfer',
    ' Missing Label': 'missing_label',
    'Shine': 'shine',
    'Skip Stitch': 'skip_stitch',
    'Pleat': 'pleat',
    'Dirt Marck': 'dirt_marck',
    'Missing operation': 'missing_operation',
    'Stain/OIL/SOIL': 'stain_oil_soil',
    'Contamination': 'contamination',
    'Construction Defect': 'construction_defect',
    'Mill Flaw': 'mill_flaw',
    'Fabric Run': 'fabric_run',
    'Misplaced': 'misplaced',
    'Puckering': 'pucketing',
    'Slanted': 'slanted',
    'Defects Sticker inside': 'defect_sticker_inside',
    'Roping': 'roping',
    'Label Slanted': 'label_slanted',
    'Shadding': 'shadding',
    'Missing Packing Trims': 'missing_packing_trims',
    'Missing Print/Embroidery': 'missing_print_or_embroidery',
    'Wrong Packing Trims': 'wrong_packing_trims',
    'Wrong PO': 'wrong_po',
    'Wrong Folding Method': 'wrong_folding_method',
    'Wrong Size Attached': 'wrong_size_attached',
    'Damaged Label': 'damaged_label',
    'Pocket Label': 'pocket_label',
    'Label Placement': 'label_placement',
    'Missing Information Lebel': 'missing_information_label',
}

QC_FA_PLANT_NUMERIC_COLUMNS = [
    "week", "team", "po", "batch", "seconds", "accepted", "rejected", "sample", "aql", "qty"
]

QC_FA_PLANT_NOT_NUMERIC_COLUMNS = [
    'date_1', 'customer', 'coord', 'date_2', 'style', 'color', 'pass_or_fail'
]

QC_FA_PLANT_AMOUNT_DEFEACTS_FIELDS = [
    'uneven', 'broken_stitch', 'open_seam', 'tear', 'hi_low', 'run_off_stitch', 'raw_edge', 'neddle_holes',
    'loose_thread', 'uncut_thread', 'big_or_littler_neck', 'uneven_neck_or_sleeve', 'out_of_measurements',
    'incorrect_stitch', 'variation_tension_sttich', 'excess_fabric', 'hitched', 'po_midex',
    'transfer_peel_off_or_leave', 'wrong_transfer', 'wrong_label', 'missing_transfer', 'missing_label', 'shine', 'skip_stitch',
    'pleat', 'dirt_marck', 'missing_operation', 'stain_oil_soil', 'contamination', 'construction_defect',
    'mill_flaw', 'fabric_run', 'misplaced', 'pucketing', 'slanted', 'defect_sticker_inside', 'roping',
    'label_slanted', 'shadding', 'missing_packing_trims', 'missing_print_or_embroidery', 'wrong_packing_trims',
    'wrong_po', 'wrong_folding_method', 'wrong_size_attached', 'damaged_label', 'pocket_label', 'label_placement',
    'missing_information_label'
]

QC_FA_CUSTOMER_REMAP = {
    'Week': 'week',
    'Customer': 'customer',
    'Line': 'team',
    'Date': 'date_1',
    'PO#': 'po',
    'Style': 'style',
    'ArtCode': 'coord',
    'Batch': 'batch',
    'Color': 'color',
    'Quantity': 'qty',
    'Seconds': 'seconds',
    'Accepted': 'accepted',
    'Rejected': 'rejected',
    'Sample': 'sample',
    'Defects': 'defeacts',
    'AQL %': 'aql',
    'Pass/Fail': 'pass_or_fail',
    'Uneven': 'uneven',
    'Broken Stitch': 'broken_stitch',
    'Open seam': 'open_seam',
    'Hi Low': 'hi_low',
    'Run Off Stitch': 'run_off_stitch',
    'Raw Edge': 'raw_edge',
    'Needle Holes': 'neddle_holes',
    'Tear': 'tear',
    'Loose Thread': 'loose_thread',
    'Uncut Thread': 'uncut_thread',
    'Big/Litter Neck': 'big_or_littler_neck',
    'Uneven Sleeve': 'uneven_neck_or_sleeve',
    'Out of Measurements': 'out_of_measurements',
    'Variation Tension Stitch': 'variation_tension_sttich',
    'Excess Fabric': 'excess_fabric',
    'Hitched': 'hitched',
    'PO Mixed': 'po_midex',
    'Transfer Peel off, Leve': 'transfer_peel_off_or_leave',
    'Wrong  Transfer': 'wrong_transfer',
    ' Missing Transfer': 'missing_transfer',
    'Missing information Label': 'missing_information_label',
    'Wrong  Label': 'wrong_label',
    'Damaged Label': 'damaged_label',
    ' Missing Label': 'missing_label',
    'Shine': 'shine',
    'Skip Stitch': 'skip_stitch',
    'Pleat': 'pleat',
    'Dirt Marck': 'dirt_marck',
    'Missing operation': 'missing_operation',
    'Stain/Oil/Soil': 'stain_oil_soil',
    'Contamination': 'contamination',
    'Construction Defect': 'construction_defect',
    'Mill Flaw': 'mill_flaw',
    'Fabric Run': 'fabric_run',
    'Puckering': 'pucketing',
    'Slanted': 'slanted',
    'Pocket': 'pocket_label',
    'Defects Sticker inside': 'defect_sticker_inside',
    'Label Slanted': 'label_slanted',
    'Shadding': 'shadding',
    'Missing Packing Trims': 'missing_packing_trims',
    'Missing Print/Embroidery': 'missing_print_or_embroidery',
    'Wrong Packing Trims': 'wrong_packing_trims',
    'Wrong PO': 'wrong_po',
    'Wrong Folding Method': 'wrong_folding_method',
    'Wrong Size Attached': 'wrong_size_attached',
    'Label Placement': 'label_placement',
}

QC_FA_CUSTOMER_NUMERIC_COLUMNS = [
    "week", "team", "po", "batch", "seconds", "accepted", "rejected", "sample", "aql", "qty"
]

QC_FA_CUSTOMER_NOT_NUMERIC_COLUMNS = [
    'date_1', 'customer', 'coord', 'date_2', 'style', 'color', 'pass_or_fail'
]

QC_FA_CUSTOMER_AMOUNT_DEFEACTS_FIELDS = [
    'uneven', 'broken_stitch', 'open_seam', 'tear', 'hi_low', 'run_off_stitch', 'raw_edge', 'neddle_holes',
    'loose_thread', 'uncut_thread', 'big_or_littler_neck', 'uneven_neck_or_sleeve', 'out_of_measurements',
    'incorrect_stitch', 'variation_tension_sttich', 'excess_fabric', 'hitched', 'po_midex',
    'transfer_peel_off_or_leave', 'wrong_transfer', 'wrong_label', 'missing_transfer', 'missing_label', 'shine', 'skip_stitch',
    'pleat', 'dirt_marck', 'missing_operation', 'stain_oil_soil', 'contamination', 'construction_defect',
    'mill_flaw', 'fabric_run', 'misplaced', 'pucketing', 'slanted', 'defect_sticker_inside', 'roping',
    'label_slanted', 'shadding', 'missing_packing_trims', 'missing_print_or_embroidery', 'wrong_packing_trims',
    'wrong_po', 'wrong_folding_method', 'wrong_size_attached', 'damaged_label', 'pocket_label', 'label_placement',
    'missing_information_label'
]
