# Generated by Django 5.2.12 on 2026-04-03 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mockup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('side', models.CharField(choices=[('FRONT', 'Front Side'), ('BACK', 'Back Side')], default='FRONT', max_length=10)),
                ('image', models.ImageField(upload_to='mockups/')),
                ('width', models.IntegerField(default=1024)),
                ('height', models.IntegerField(default=768)),
            ],
            options={
                'ordering': ['name', 'side'],
            },
        ),
        migrations.CreateModel(
            name='InspectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('week', models.PositiveIntegerField(editable=False)),
                ('style', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('is_closed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PASS', 'Pass'), ('REJECT', 'Reject')], default='OPEN', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality_data.color')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevisionDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_size', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('defect_count', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('coordinates_x', models.JSONField(default=list)),
                ('coordinates_y', models.JSONField(default=list)),
                ('defect_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quality_data.defecttype')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_data.inspectiondata')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
