# Generated by Django 5.2.12 on 2026-03-30 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mockup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='mockups/')),
                ('width', models.IntegerField(default=1024)),
                ('height', models.IntegerField(default=768)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quality_data.color')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevisionDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defectSize', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('defectCount', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('coordinates_x', models.JSONField(default=list)),
                ('coordinates_y', models.JSONField(default=list)),
                ('defectType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quality_data.defecttype')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_data.inspectiondata')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
