# Generated by Django 5.2.12 on 2026-04-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiondata',
            name='lot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
