# Generated by Django 5.2.12 on 2026-03-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
