# Generated by Django 5.2.13 on 2026-04-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_data', '0003_alter_inspectiondata_inspector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisiondefect',
            name='defect_size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
